---@type LazyPluginSpec
return {
  "CopilotC-Nvim/CopilotChat.nvim",
  build = "make tiktoken",
  cmd = {
    "CopilotChat",
    "CopilotChatClose",
    "CopilotChatCommit",
    "CopilotChatCommitStaged",
    "CopilotChatDebugInfo",
    "CopilotChatDocs",
    "CopilotChatExplain",
    "CopilotChatFix",
    "CopilotChatFixDiagnostic",
    "CopilotChatLoad",
    "CopilotChatModel",
    "CopilotChatModels",
    "CopilotChatOpen",
    "CopilotChatOptimize",
    "CopilotChatReset",
    "CopilotChatSave",
    "CopilotChatStop",
    "CopilotChatTests",
    "CopilotChatToggle",
  },
  dependencies = {
    require "plugins.copilot",
    require "plugins.plenary",
  },
  opts = {},
}
